AW4.localize["es-ES"] = {
        "launching"             : "Iniciando IBM Aspera Connect...",
        "install-on-safari"     : "Una vez que IBM Aspera Connect esté instalada, reinicie el navegador.",
        "retry-button"          : "Reintentar",
        "retry"                 : "No se puede acceder a Connect",
        "security-update"       : "IBM Aspera Connect necesita una actualización de seguridad.",
        "running"               : "IBM Aspera Connect se está ejecutando",
        "download-latest-button": "Descargar última versión",
        "downloading"           : "Descargando el instalador de Connect",
        "continue-button"       : "Continuar de todas formas",
        "already-installed"     : "¿Ya está instalado?",
        "troubleshoot"          : "Resolver problemas",
        "refresh-button"        : "Renovar",
        "ext-install"           : "Las subidas y las descargas requieren IBM Aspera Connect.",
        "run-installer"         : "Ejecutar el instalador de Connect.",
        "install-addon"         : "Instalar el complemento",
        "welcome"               : "Bienvenido",
        "install-ext"           : "Instalar la extensión",
        "download-connect"      : "Descargar Connect",
        "install-connect"       : "Instalar Connect",
        "not-supported"         : "Este navegador no tiene el soporte de IBM Aspera Connect. Para ver una lista de los navegadores soportados, <a>pulse aquí</a>.",
        "update-required"       : "Este sitio necesita una versión más reciente de IBM Aspera Connect.",
        "download-fail"         : "¿Ha fallado la descarga?",
        "install-finished"      : "¿Ha finalizado la instalación?",

        "setup-title"           : "Configuración de IBM Aspera Connect",
        "double-click"          : "Realice una doble pulsación para instalar",
        "setup-intro"           : "Para instalar <b>IBM Aspera Connect</b>, pulse <b>Iniciar</b>",
        "start"                 : "Iniciar",
        "license-agreement-link": "Al hacer la instalación, acepta el <a>Acuerdo de licencia</a> de IBM Aspera.",
        "license-agreement"     : "Acuerdo de licencia",
        "back"                  : "Volver",
        "installing-connect"    : "Instalando <b>IBM Aspera Connect</b>...",
        "install-completed"     : "La instalación se ha completado.",
        "install-failed"        : "La instalación ha fallado.",
        "close"                 : "Cerrar",
        "sorry"                 : "Lo siento, no hemos podido instalar Connect en este momento.",
        "open-logs"             : "Abrir registros",

        "firefox-description"   : "Este complemento permite el uso de IBM Aspera Connect con Firefox. Este complemento requiere la aplicación IBM Aspera Connect, versión 3.9.0 o superior.",
        "chrome-description"    : "Esta extensión permite el uso de IBM Aspera Connect con Chrome. Esta extensión requiere la aplicación IBM Aspera Connect, versión 3.9.0 o superior.",
        "edge-description"      : "Esta extensión permite el uso de IBM Aspera Connect con Edge. Esta extensión requiere la aplicación IBM Aspera Connect, versión 3.9.0 o superior."
};

