export const Dictionary = {
  launching        : 'Launching IBM Aspera Connect...',
  restartBanner  : 'Once IBM Aspera Connect is installed, please restart the browser.',
  retryButton      : 'Retry',
  retry            : 'Cannot reach Connect',
  running          : 'IBM Aspera Connect is running!',
  alreadyInstalled : 'Already installed?',
  troubleshoot     : 'Troubleshoot',
  refreshButton    : 'Refresh',
  bannerTitle      : 'To enable Aspera uploads and downloads, you need to install or upgrade to IBM Aspera Connect {3.9.1}.',
  tryRestarting    : 'Or, try restarting the browser.',
  pleaseDownload   : 'Please wait. Downloading the Connect app installer...',
  runInstaller     : 'Please run the Connect app installer',
  stepOne          : 'Step 1',
  stepTwo          : 'Step 2',
  stepThree        : 'Step 3',
  how              : 'How?',
  new              : 'New',
  installAddon     : 'Install add-on',
  installExtension : 'Install Extension',
  enableExtension  : 'Enable Extension',
  required         : 'Required Steps',
  downloadConnect  : 'Download Connect',
  downloadApp      : 'Download the App',
  installConnect   : 'Install Connect',
  upgradeConnect   : 'Upgrade Connect',
  notSupported     : 'This browser is not supported by IBM Aspera Connect. For a list of supported browsers, <a>click here</a>.',
  previousVersion  : 'Try returning to previous version.'
};
