export const Dictionary = {
  launching        : 'Iniciando IBM Aspera Connect...',
  installOnSafari  : 'Una vez que IBM Aspera Connect esté instalada, reinicie el navegador.',
  retryButton      : 'Reintentar',
  retry            : 'No se puede acceder a Connect',
  running          : 'IBM Aspera Connect se está ejecutando',
  alreadyInstalled : '¿Ya está instalado?',
  troubleshoot     : 'Resolver problemas',
  refreshButton    : 'Renovar',
  bannerTitle      : 'Para habilitar las cargas y descargas de Aspera, debe instalar o actualizar IBM Aspera Connect {3.9.1}.',
  tryRestarting    : 'O bien, reinicie el navegador.',
  pleaseDownload   : 'Espere. Descargando el instalador de la aplicación Connect...',
  runInstaller     : 'Ejecute el instalador de la aplicación Connect',
  stepOne          : 'Paso 1',
  stepTwo          : 'Paso 2',
  stepThree        : 'Paso 3',
  how              : '¿Cómo?',
  new              : 'Nuevo',
  installAddon     : 'Instalar el complemento',
  installExtension : 'Instalar la extensión',
  enableExtension  : 'Habilitar la extensión',
  required         : 'Pasos necesarios',
  downloadConnect  : 'Descargar Connect',
  downloadApp      : 'Descargar la aplicación',
  installConnect   : 'Instalar Connect',
  upgradeConnect   : 'Actualizar Connect',
  notSupported     : 'Este navegador no tiene el soporte de IBM Aspera Connect. Para ver una lista de los navegadores soportados, <a>pulse aquí</a>.',
  previousVersion  : 'Intente volver a la versión anterior.'
};
