export const Dictionary = {
  launching        : "Lancement d'IBM Aspera Connect...",
  restartBanner  : "Une fois IBM Aspera Connect installé, redémarrez le navigateur.",
  retryButton      : "Nouvelle tentative",
  retry            : "Impossible d'atteindre Connect",
  running          : "IBM Aspera Connect est en cours d'exécution !",
  alreadyInstalled : "Déjà installé ?",
  troubleshoot     : "Traitement des incidents",
  refreshButton    : "Actualiser",
  bannerTitle      : "Pour activer les envois et réceptions par téléchargement d'Aspera, vous devez installer ou mettre à niveau IBM Aspera Connect {3.9.1}.",
  tryRestarting    : "Vous pouvez aussi essayer de redémarrer le navigateur.",
  pleaseDownload   : "Veuillez patienter. Téléchargement du programme d'installation de l'application Connect...",
  runInstaller     : "Veuillez exécuter le programme d'installation de l'application Connect.",
  stepOne          : "Etape 1",
  stepTwo          : "Etape 2",
  stepThree        : "Etape 3",
  how              : "Comment ?",
  new              : "Nouveau",
  installAddon     : "Installer le module complémentaire",
  installExtension : "Installer l'extension",
  enableExtension  : "Activer l'extension",
  required         : "Etapes obligatoires",
  downloadConnect  : "Télécharger Connect",
  downloadApp      : "Télécharger l'application",
  installConnect   : "Installer Connect",
  upgradeConnect   : "Mettre à niveau Connect",
  notSupported     : "Ce navigateur n'est pas pris en charge par IBM Aspera Connect. <a>Cliquez ici</a> pour voir la liste des navigateurs pris en charge.",
  previousVersion  : "Essayez de revenir à la version précédente."
};
