export const Dictionary = {
  launching        : 'IBM Aspera Connect を起動しています...',
  installOnSafari  : 'IBM Aspera Connect がインストールされたら、ブラウザーを再始動してください。',
  retryButton      : 'リトライ',
  retry            : 'Connect に到達できません',
  running          : 'IBM Aspera Connect は実行中です!',
  alreadyInstalled : 'インストール済みですか?',
  troubleshoot     : 'トラブルシューティング',
  refreshButton    : '更新',
  bannerTitle      : 'Aspera のアップロードとダウンロードを有効にするには、IBM Aspera Connect {3.9.1} をインストールするか、このバージョンにアップグレードする必要があります。',
  tryRestarting    : 'または、ブラウザーを再始動してください。',
  pleaseDownload   : 'お待ちください。 Connect アプリケーション・インストーラーをダウンロードしています...',
  runInstaller     : 'Connect アプリケーション・インストーラーを実行してください。',
  stepOne          : 'ステップ 1',
  stepTwo          : 'ステップ 2',
  stepThree        : 'ステップ 3',
  how              : '方法',
  new              : '新規',
  installAddon     : 'アドオンのインストール',
  installExtension : '拡張機能のインストール',
  enableExtension  : '拡張機能の有効化',
  required         : '必須ステップ',
  downloadConnect  : 'Connect のダウンロード',
  downloadApp      : 'アプリケーションのダウンロード',
  installConnect   : 'Connect のインストール',
  upgradeConnect   : 'Connect のアップグレード',
  notSupported     : 'このブラウザーは、IBM Aspera Connect でサポートされていません。 サポートされるブラウザーのリストについては、<a>ここをクリック</a>してください。',
  previousVersion  : '前のバージョンに戻す'
};
