export const Dictionary = {
  launching        : "IBM Aspera Connect 시작 중...",
  installOnSafari  : "IBM Aspera Connect가 설치되면 브라우저를 다시 시작하십시오.",
  retryButton      : "재시도",
  retry            : "Connect에 연결할 수 없음",
  running          : "IBM Aspera Connect가 실행 중입니다!",
  alreadyInstalled : "이미 설치하셨습니까?",
  troubleshoot     : "문제점 해결",
  refreshButton    : "새로 고치기",
  bannerTitle      : "Aspera 업로드 및 다운로드를 사용하려면 IBM Aspera Connect {3.9.1}을 설치 또는 업그레이드해야 합니다.",
  tryRestarting    : "브라우저를 다시 시작해 보십시오.",
  pleaseDownload   : "잠시 대기하십시오. Connect 앱 설치 프로그램을 다운로드하는 중입니다...",
  runInstaller     : "Connect 앱 설치 프로그램을 실행하십시오.",
  stepOne          : "1단계",
  stepTwo          : "2단계",
  stepThree        : "3단계",
  how              : "방법",
  new              : "신규",
  installAddon     : "추가 기능 설치",
  installExtension : "확장 기능 설치",
  enableExtension  : "확장 기능 사용",
  required         : "필수 단계",
  downloadConnect  : "Connect 다운로드",
  downloadApp      : "앱 다운로드",
  installConnect   : "Connect 설치",
  upgradeConnect   : "Connect 업그레이드",
  notSupported     : "이 브라우저는 IBM Aspera Connect에서 지원하지 않습니다. 지원되는 브라우저 목록은 <a>여기를 클릭</a>하십시오.",
  previousVersion  : "이전 버전으로 돌아가십시오."
};
