export const Dictionary = {
  launching        : "IBM Aspera Connect wordt gestart ...",
  installOnSafari  : "Start de browser opnieuw zodra IBM Aspera Connect geïnstalleerd is.",
  retryButton      : "Opnieuw proberen",
  retry            : "Connect is niet bereikbaar",
  running          : "IBM Aspera Connect is actief!",
  alreadyInstalled : "Al geïnstalleerd?",
  troubleshoot     : "Problemen oplossen",
  refreshButton    : "Vernieuwen",
  bannerTitle      : "Om uploads en downloads van Aspera in te schakelen, moet u IBM Aspera Connect {3.9.1} installeren of upgraden.",
  tryRestarting    : "Of probeer de browser opnieuw te starten.",
  pleaseDownload   : "Even geduld a.u.b. Het installatieprogramma voor de Connect-app wordt gedownload ...",
  runInstaller     : "Voer het programma voor installatie van de app Connect uit",
  stepOne          : "Stap 1",
  stepTwo          : "Stap 2",
  stepThree        : "Stap 3",
  how              : "Hoe?",
  new              : "Nieuw",
  installAddon     : "Addon installeren",
  installExtension : "Extensie installeren",
  enableExtension  : "Extensie inschakelen",
  required         : "Vereiste stappen",
  downloadConnect  : "Connect downloaden",
  downloadApp      : "App downloaden",
  installConnect   : "Connect installeren",
  upgradeConnect   : "Connect upgraden",
  notSupported     : "Deze browser wordt niet ondersteund door IBM Aspera Connect. Voor een lijst van ondersteunde browsers <a>klikt u hier</a>.",
  previousVersion  : "Probeer terug te keren naar de vorige versie.",
};
