export const Dictionary = {
  launching        : '正在启动 IBM Aspera Connect...',
  restartBanner    : 'IBM Aspera Connect 安装完成后，请重新启动浏览器。',
  restartFooter    : 'Restart the browser once the upgrade is complete.',
  retryButton      : '重试',
  retry            : '无法连接 Connect',
  running          : 'IBM Aspera Connect 正在运行！',
  alreadyInstalled : '已安装？',
  troubleshoot     : '疑难解答',
  refreshButton    : '刷新',
  bannerTitle      : '要启用 Aspera 上传和下载，您需要安装或升级至 IBM Aspera Connect {3.9.1}。',
  tryRestarting    : '或者，请尝试重新启动浏览器。',
  pleaseDownload   : '请稍等。正在下载 Connect 应用安装程序...',
  runInstaller     : '请运行 Connect 应用安装程序',
  stepOne          : '第 1 步',
  stepTwo          : '第 2 步',
  stepThree        : '第 3 步',
  how              : '如何？',
  new              : '新的',
  installAddon     : '安装附加组件',
  installExtension : '安装扩展',
  enableExtension  : '启用扩展',
  required         : '必要步骤',
  downloadConnect  : '下载 Connect',
  downloadApp      : '下载应用',
  installConnect   : '安装 Connect',
  upgradeConnect   : '升级 Connect',
  notSupported     : 'IBM Aspera Connect 不支持此浏览器。要获取受支持浏览器列表，请<a>单击此处</a>。',
  previousVersion  : '尝试返回至先前版本。'
};
