AW4.localize["ko-KR"] = {
        "launching"             : "IBM Aspera Connect 시작 중...",
        "install-on-safari"     : "IBM Aspera Connect가 설치되면 브라우저를 다시 시작하십시오.",
        "retry-button"          : "재시도",
        "retry"                 : "Connect에 연결할 수 없음",
        "security-update"       : "IBM Aspera Connect에 보안 업데이트가 필요합니다.",
        "running"               : "IBM Aspera Connect가 실행 중입니다!",
        "download-latest-button": "최신 버전 다운로드",
        "downloading"           : "Connect 설치 프로그램 다운로드 중",
        "continue-button"       : "계속하기",
        "already-installed"     : "이미 설치하셨습니까?",
        "troubleshoot"          : "문제점 해결",
        "refresh-button"        : "새로 고치기",
        "ext-install"           : "Aspera 업로드 및 다운로드를 사용하려면 IBM Aspera Connect {3.9.1}을 설치 또는 업그레이드해야 합니다.",
        "please-download"       : "잠시 대기하십시오. Connect 앱 설치 프로그램을 다운로드하는 중입니다...",
        "run-installer"         : "Connect 앱 설치 프로그램을 실행하십시오.",
        "step-1"                : "1단계",
        "step-2"                : "2단계",
        "step-3"                : "3단계",
        "how"                   : "방법",
        "new"                   : "신규",
        "install-addon"         : "추가 기능 설치",
        "install-extension"     : "확장 기능 설치",
        "enable-extension"      : "확장 기능 사용",
        "required"              : "필수 단계",
        "install-ext"           : "확장 기능 설치",
        "download-connect"      : "Connect 다운로드",
        "download-app"          : "앱 다운로드",
        "install-connect"       : "Connect 설치",
        "upgrade-connect"       : "Connect 업그레이드",
        "not-supported"         : "이 브라우저는 IBM Aspera Connect에서 지원하지 않습니다. 지원되는 브라우저 목록은 <a>여기를 클릭</a>하십시오.",
        "update-required"       : "이 사이트에는 새로운 버전의 IBM Aspera Connect가 필요합니다.",
        "download-fail"         : "다운로드에 실패했습니까?",
        "install-finished"       : "설치가 완료되었습니까?",

        "setup-title"           : "IBM Aspera Connect 설치",
        "double-click"          : "설치하려면 두 번 클릭",
        "setup-intro"           : "<b>IBM Aspera Connect</b>를 설치하려면 <b>시작</b> 클릭",
        "start"                 : "시작",
        "license-agreement-link": "설치하여 IBM Aspera <a>라이센스 계약</a>에 동의합니다.",
        "license-agreement"     : "라이센스 계약",
        "back"                  : "되돌아가기",
        "installing-connect"    : "<b>IBM Aspera Connect</b> 설치 중...",
        "install-completed"     : "설치가 완료되었습니다!",
        "install-failed"        : "설치에 실패했습니다.",
        "close"                 : "닫기",
        "sorry"                 : "죄송합니다. 지금은 Connect를 설치할 수 없습니다.",
        "open-logs"             : "로그 열기",

        "firefox-description"    : "이 추가 기능은 Firefox에서 IBM Aspera Connect를 사용 가능하게 합니다. 이 추가 기능에는 IBM Aspera Connect 애플리케이션, 버전 3.9.0 이상이 필요합니다.",
        "chrome-description"    : "이 확장은 Chrome에서 IBM Aspera Connect를 사용 가능하게 합니다. 이 확장에는 IBM Aspera Connect 애플리케이션, 버전 3.9.0 이상이 필요합니다.",
        "edge-description"      : "이 확장은 Edge에서 IBM Aspera Connect를 사용 가능하게 합니다. 이 확장에는 IBM Aspera Connect 애플리케이션, 버전 3.9.0 이상이 필요합니다."
};
