AW4.localize["en-US"] = {
        "launching"             : "Launching IBM Aspera Connect...",
        "install-on-safari"     : "Once IBM Aspera Connect is installed, please restart the browser.",
        "retry-button"          : "Retry",
        "retry"                 : "Cannot reach Connect",
        "security-update"       : "IBM Aspera Connect requires a security update.",
        "running"               : "IBM Aspera Connect is running!",
        "download-latest-button": "Download latest version",
        "downloading"           : "Downloading Connect installer",
        "continue-button"       : "Continue anyway",
        "already-installed"     : "Already installed?",
        "troubleshoot"          : "Troubleshoot",
        "refresh-button"        : "Refresh",
        "ext-install"           : "To enable Aspera uploads and downloads, you need to install or upgrade to IBM Aspera Connect {3.9.1}.",
        "try-restarting"        : "Or, try restarting the browser.",
        "please-download"       : "Please wait. Downloading the Connect app installer...",
        "run-installer"         : "Please run the Connect app installer",
        "step-1"                : "Step 1",
        "step-2"                : "Step 2",
        "step-3"                : "Step 3",
        "how"                   : "How?",
        "new"                   : "New",
        "install-addon"         : "Install add-on",
        "install-extension"     : "Install Extension",
        "enable-extension"      : "Enable Extension",
        "required"              : "Required Steps",
        "install-ext"           : "Install extension",
        "download-connect"      : "Download Connect",
        "download-app"          : "Download the App",
        "install-connect"       : "Install Connect",
        "upgrade-connect"       : "Upgrade Connect",
        "not-supported"         : "This browser is not supported by IBM Aspera Connect. For a list of supported browsers, <a>click here</a>.",
        "update-required"       : "This site requires a newer version of IBM Aspera Connect.",
        "download-fail"         : "Download failed?",
        "install-finished"       : "Install finished?",

        "setup-title"           : "IBM Aspera Connect Setup",
        "double-click"          : "Double-click to install",
        "setup-intro"           : "To install <b>IBM Aspera Connect</b>, click <b>Start</b>",
        "start"                 : "Start",
        "license-agreement-link": "By installing, you agree to the IBM Aspera <a>license agreement</a>.",
        "license-agreement"     : "License agreement",
        "back"                  : "Go back",
        "installing-connect"    : "Installing <b>IBM Aspera Connect</b>...",
        "install-completed"     : "Installation completed!",
        "install-failed"        : "Installation failed.",
        "close"                 : "Close",
        "sorry"                 : "Sorry, we could not install Connect at this time.",
        "open-logs"             : "Open logs",
        "previous-version"      : "Try returning to previous version.",

        "firefox-description"    : "This add-on enables the use of IBM Aspera Connect with Firefox. This add-on requires the IBM Aspera Connect application, version 3.9.0 or newer.",
        "chrome-description"    : "This extension enables the use of IBM Aspera Connect with Chrome. This extension requires the IBM Aspera Connect application, version 3.9.0 or newer.",
        "edge-description"      : "This extension enables the use of IBM Aspera Connect with Edge. This extension requires the IBM Aspera Connect application, version 3.9.0 or newer."
};
