AW4.localize["ja-JP"] = {
        "launching"             : "IBM Aspera Connect を起動しています...",
        "install-on-safari"     : "IBM Aspera Connect がインストールされたら、ブラウザーを再始動してください。",
        "retry-button"          : "リトライ",
        "retry"                 : "Connect に到達できません",
        "security-update"       : "IBM Aspera Connect のセキュリティーを更新する必要があります。",
        "running"               : "IBM Aspera Connect は実行中です!",
        "download-latest-button": "最新バージョンのダウンロード",
        "downloading"           : "Connect のインストーラーをダウンロード中です",
        "continue-button"       : "続行する",
        "already-installed"     : "インストール済みですか?",
        "troubleshoot"          : "トラブルシューティング",
        "refresh-button"        : "更新",
        "ext-install"           : "Aspera のアップロードとダウンロードを有効にするには、IBM Aspera Connect {3.9.1} にインストールするか、このバージョンにアップグレードする必要があります。",
        "please-download"       : "お待ちください。Connect アプリケーション・インストーラーをダウンロードしています...",
        "run-installer"         : "Connect アプリケーション・インストーラーを実行してください。",
        "step-1"                : "ステップ 1",
        "step-2"                : "ステップ 2",
        "step-3"                : "ステップ 3",
        "how"                   : "方法",
        "new"                   : "新規",
        "install-addon"         : "アドオンのインストール",
        "install-extension"     : "拡張機能のインストール",
        "enable-extension"      : "拡張機能の有効化",
        "required"              : "必須ステップ",
        "install-ext"           : "拡張機能のインストール",
        "download-connect"      : "Connect のダウンロード",
        "download-app"          : "アプリケーションのダウンロード",
        "install-connect"       : "Connect のインストール",
        "upgrade-connect"       : "Connect のアップグレード",
        "not-supported"         : "このブラウザーは、IBM Aspera Connect でサポートされていません。 サポートされるブラウザーのリストについては、<a>ここをクリック</a>してください。",
        "update-required"       : "このサイトには新しいバージョンの IBM Aspera Connect が必要です。",
        "download-fail"         : "ダウンロード・エラーになりましたか?",
        "install-finished"       : "インストールは完了していますか?",

        "setup-title"           : "IBM Aspera Connect のセットアップ",
        "double-click"          : "ダブルクリックしてインストール",
        "setup-intro"           : "<b>IBM Aspera Connect</b> をインストールするには、<b>「開始」</b>をクリックしてください",
        "start"                 : "開始",
        "license-agreement-link": "インストールすることによって、IBM Aspera の<a>ご使用条件</a>に同意したことになります。",
        "license-agreement"     : "ご使用条件",
        "back"                  : "戻る",
        "installing-connect"    : "<b>IBM Aspera Connect</b> をインストールしています...",
        "install-completed"     : "インストールが完了しました。",
        "install-failed"        : "インストールできませんでした。",
        "close"                 : "閉じる",
        "sorry"                 : "申し訳ありません。今回は Connect をインストールできませんでした。",
        "open-logs"             : "ログを開く",

        "firefox-description"    : "このアドオンによって IBM Aspera Connect を Firefox で使用できるようになります。 アドオンには、IBM Aspera Connect アプリケーションのバージョン 3.9.0 以降が必要です。",
        "chrome-description"    : "この拡張機能によって IBM Aspera Connect を Chrome で使用できるようになります。 拡張機能には、IBM Aspera Connect アプリケーションのバージョン 3.9.0 以降が必要です。",
        "edge-description"      : "この拡張機能によって IBM Aspera Connect を Edge で使用できるようになります。 拡張機能には、IBM Aspera Connect アプリケーションのバージョン 3.9.0 以降が必要です。"
};
