AW4.localize["fr-FR"] = {
        "launching"             : "Lancement d'IBM Aspera Connect...",
        "install-on-safari"     : "Une fois IBM Aspera Connect installé, redémarrez le navigateur.",
        "retry-button"          : "Nouvelle tentative",
        "retry"                 : "Impossible d'atteindre Connect",
        "security-update"       : "IBM Aspera Connect nécessite une mise à jour de sécurité.",
        "running"               : "IBM Aspera Connect est en cours d'exécution !",
        "download-latest-button": "Télécharger la version la plus récente",
        "downloading"           : "Téléchargement du programme d'installation Connect",
        "continue-button"       : "Continuer malgré tout",
        "already-installed"     : "Déjà installé ?",
        "troubleshoot"          : "Traitement des incidents",
        "refresh-button"        : "Actualiser",
        "ext-install"           : "Pour activer les envois et réceptions par téléchargement d'Aspera, vous devez installer ou mettre à niveau IBM Aspera Connect {3.9.1}.",
        "please-download"       : "Veuillez patienter. Téléchargement du programme d'installation de l'application Connect...",
        "run-installer"         : "Veuillez exécuter le programme d'installation de l'application Connect.",
        "step-1"                : "Etape 1",
        "step-2"                : "Etape 2",
        "step-3"                : "Etape 3",
        "how"                   : "Comment ?",
        "new"                   : "Nouveau",
        "install-addon"         : "Installer le module complémentaire",
        "install-extension"     : "Installer l'extension",
        "enable-extension"      : "Activer l'extension",
        "required"              : "Etapes obligatoires",
        "install-ext"           : "Installer l'extension",
        "download-connect"      : "Télécharger Connect",
        "download-app"          : "Télécharger l'application",
        "install-connect"       : "Installer Connect",
        "upgrade-connect"       : "Mettre à niveau Connect",
        "not-supported"         : "Ce navigateur n'est pas pris en charge par IBM Aspera Connect. <a>Cliquez ici</a> pour voir la liste des navigateurs pris en charge.",
        "update-required"       : "Ce site nécessite une version plus récente d'IBM Aspera Connect.",
        "download-fail"         : "Echec du téléchargement ?",
        "install-finished"       : "Installation terminée ?",

        "setup-title"           : "Configuration d'IBM Aspera Connect",
        "double-click"          : "Cliquez deux fois pour effectuer l'installation",
        "setup-intro"           : "Pour installer <b>IBM Aspera Connect</b>, cliquez sur <b>Démarrer</b>",
        "start"                 : "Démarrer",
        "license-agreement-link": "En installant IBM Aspera, vous acceptez le <a>contrat de licence</a>.",
        "license-agreement"     : "Contrat de licence",
        "back"                  : "Retour",
        "installing-connect"    : "Installation d'<b>IBM Aspera Connect</b>...",
        "install-completed"     : "Installation terminée !",
        "install-failed"        : "Échec de l'installation.",
        "close"                 : "Fermer",
        "sorry"                 : "Désolé, nous ne pouvons pas installer Connect pour le moment.",
        "open-logs"             : "Ouvrir les journaux",

        "firefox-description"    : "Ce module complémentaire permet d'utiliser IBM Aspera Connect avec Firefox. Il nécessite l'application IBM Aspera Connect version 3.9.0 ou ultérieure.",
        "chrome-description"    : "Cette extension permet d'utiliser IBM Aspera Connect avec Chrome. Elle nécessite l'application IBM Aspera Connect version 3.9.0 ou ultérieure.",
        "edge-description"      : "Cette extension permet d'utiliser IBM Aspera Connect avec Edge. Elle nécessite l'application IBM Aspera Connect version 3.9.0 ou ultérieure."
};
