AW4.localize["zh-CN"] = {
        "launching"             : "正在启动 IBM Aspera Connect...",
        "install-on-safari"     : "IBM Aspera Connect 安装完成后，请重新启动浏览器。",
        "retry-button"          : "重试",
        "retry"                 : "无法连接 Connect",
        "security-update"       : "IBM Aspera Connect 需要进行安全性更新。",
        "running"               : "IBM Aspera Connect 正在运行！",
        "download-latest-button": "下载最新版本",
        "downloading"           : "正在下载 Connect 安装程序",
        "continue-button"       : "无论如何都继续",
        "already-installed"     : "已安装？",
        "troubleshoot"          : "疑难解答",
        "refresh-button"        : "刷新",
        "ext-install"           : "要启用 Aspera 上传和下载，您必须安装或升级 IBM Aspera Connect {3.9.1}。",
        "please-download"       : "请稍等。正在下载 Connect 应用安装程序...",
        "run-installer"         : "请运行 Connect 应用安装程序",
        "step-1"                : "第 1 步",
        "step-2"                : "第 2 步",
        "step-3"                : "第 3 步",
        "how"                   : "如何？",
        "new"                   : "新的",
        "install-addon"         : "安装附加组件",
        "install-extension"     : "安装扩展",
        "enable-extension"      : "启用扩展",
        "required"              : "必要步骤",
        "install-ext"           : "安装扩展",
        "download-connect"      : "下载 Connect",
        "download-app"          : "下载应用",
        "install-connect"       : "安装 Connect",
        "upgrade-connect"       : "升级 Connect",
        "not-supported"         : "IBM Aspera Connect 不支持此浏览器。要获取受支持浏览器列表，请<a>单击此处</a>。",
        "update-required"       : "本站点需要更新版本的 IBM Aspera Connect。",
        "download-fail"         : "下载失败？",
        "install-finished"       : "安装完成？",

        "setup-title"           : "IBM Aspera Connect 安装",
        "double-click"          : "双击以安装",
        "setup-intro"           : "要安装 <b>IBM Aspera Connect</b>，请单击<b>开始</b>",
        "start"                 : "开始",
        "license-agreement-link": "通过安装，即表明您同意 IBM Aspera <a>许可协议</a>。",
        "license-agreement"     : "许可协议",
        "back"                  : "后退",
        "installing-connect"    : "正在安装 <b>IBM Aspera Connect</b>...",
        "install-completed"     : "安装完成！",
        "install-failed"        : "安装失败。",
        "close"                 : "关闭",
        "sorry"                 : "很抱歉，目前我们无法安装 Connect。",
        "open-logs"             : "打开日志",

        "firefox-description"    : "此附加组件支持在 Firefox 上使用 IBM Aspera Connect。此附加组件需要 IBM Aspera Connect 应用程序 V3.9.0 或更高版本。",
        "chrome-description"    : "此扩展支持在 Chrome 上使用 IBM Aspera Connect。此扩展需要 IBM Aspera Connect 应用程序 V3.9.0 或更高版本。",
        "edge-description"      : "此扩展支持在 Edge 上使用 IBM Aspera Connect。此扩展需要 IBM Aspera Connect 应用程序 V3.9.0 或更高版本。"
};
