import Utils from './utils';

const Translations = {
  'en-US': {
    launching        : 'Launching IBM Aspera Connect...',
    installOnSafari  : "Once IBM Aspera Connect is installed, please restart the browser.",
    retryButton      : 'Retry',
    retry            : 'Cannot reach Connect',
    running          : 'IBM Aspera Connect is running!',
    alreadyInstalled : 'Already installed?',
    troubleshoot     : 'Troubleshoot' ,
    refreshButton    : 'Refresh',
    bannerTitle      : 'To enable Aspera uploads and downloads, you need to install or upgrade to IBM Aspera Connect {3.9.1}.',
    tryRestarting    : 'Or, try restarting the browser.',
    pleaseDownload   : 'Please wait. Downloading the Connect app installer...',
    runInstaller     : 'Please run the Connect app installer',
    stepOne          : 'Step 1',
    stepTwo          : 'Step 2',
    stepThree        : 'Step 3',
    how              : 'How?',
    new              : 'New',
    installAddon     : 'Install add-on',
    installExtension : 'Install Extension',
    enableExtension  : 'Enable Extension',
    required         : 'Required Steps',
    downloadConnect  : 'Download Connect',
    downloadApp      : 'Download the App',
    installConnect   : 'Install Connect',
    upgradeConnect   : 'Upgrade Connect',
    notSupported     : 'This browser is not supported by IBM Aspera Connect. For a list of supported browsers, <a>click here</a>.',
    previousVersion  : 'Try returning to previous version.'
  },
  'es': {
    launching        : 'Iniciando IBM Aspera Connect...',
    installOnSafari  : "Una vez que IBM Aspera Connect esté instalada, reinicie el navegador.",
    retryButton      : "Reintentar",
    retry            : "No se puede acceder a Connect",
    running          : "IBM Aspera Connect se está ejecutando",
    alreadyInstalled : "¿Ya está instalado?",
    troubleshoot     : "Resolver problemas",
    refreshButton    : "Renovar",
    bannerTitle      : "Para habilitar las cargas y descargas de Aspera, debe instalar o actualizar IBM Aspera Connect {3.9.1}.",
    tryRestarting    : "O bien, reinicie el navegador.",
    pleaseDownload   : "Espere. Descargando el instalador de la aplicación Connect...",
    runInstaller     : "Ejecute el instalador de la aplicación Connect",
    stepOne          : "Paso 1",
    stepTwo          : "Paso 2",
    stepThree        : "Paso 3",
    how              : "¿Cómo?",
    new              : "Nuevo",
    installAddon     : "Instalar el complemento",
    installExtension : "Instalar la extensión",
    enableExtension  : "Habilitar la extensión",
    required         : "Pasos necesarios",
    downloadConnect  : "Descargar Connect",
    downloadApp      : "Descargar la aplicación",
    installConnect   : "Instalar Connect",
    upgradeConnect   : "Actualizar Connect",
    notSupported     : "Este navegador no tiene el soporte de IBM Aspera Connect. Para ver una lista de los navegadores soportados, <a>pulse aquí</a>.",
    previousVersion  : "Intente volver a la versión anterior."
  },
  'fr': {
    launching        : "Lancement d'IBM Aspera Connect...",
    installOnSafari  : "Une fois IBM Aspera Connect installé, redémarrez le navigateur.",
    retryButton      : "Nouvelle tentative",
    retry            : "Impossible d'atteindre Connect",
    running          : "IBM Aspera Connect est en cours d'exécution !",
    alreadyInstalled : "Déjà installé ?",
    troubleshoot     : "Traitement des incidents",
    refreshButton    : "Actualiser",
    bannerTitle      : "Pour activer les envois et réceptions par téléchargement d'Aspera, vous devez installer ou mettre à niveau IBM Aspera Connect {3.9.1}.",
    tryRestarting    : "Vous pouvez aussi essayer de redémarrer le navigateur.",
    pleaseDownload   : "Veuillez patienter. Téléchargement du programme d'installation de l'application Connect...",
    runInstaller     : "Veuillez exécuter le programme d'installation de l'application Connect.",
    stepOne          : "Etape 1",
    stepTwo          : "Etape 2",
    stepThree        : "Etape 3",
    how              : "Comment ?",
    new              : "Nouveau",
    installAddon     : "Installer le module complémentaire",
    installExtension : "Installer l'extension",
    enableExtension  : "Activer l'extension",
    required         : "Etapes obligatoires",
    downloadConnect  : "Télécharger Connect",
    downloadApp      : "Télécharger l'application",
    installConnect   : "Installer Connect",
    upgradeConnect   : "Mettre à niveau Connect",
    notSupported     : "Ce navigateur n'est pas pris en charge par IBM Aspera Connect. <a>Cliquez ici</a> pour voir la liste des navigateurs pris en charge.",
    previousVersion  : "Essayez de revenir à la version précédente."
  },
  'ja': {
    launching        : "IBM Aspera Connect を起動しています...",
    installOnSafari  : "IBM Aspera Connect がインストールされたら、ブラウザーを再始動してください。",
    retryButton      : "リトライ",
    retry            : "Connect に到達できません",
    running          : "IBM Aspera Connect は実行中です!",
    alreadyInstalled : "インストール済みですか?",
    troubleshoot     : "トラブルシューティング",
    refreshButton    : "更新",
    bannerTitle      : "Aspera のアップロードとダウンロードを有効にするには、IBM Aspera Connect {3.9.1} にインストールするか、このバージョンにアップグレードする必要があります。",
    tryRestarting    : "または、ブラウザーを再始動してください。",
    pleaseDownload   : "お待ちください。Connect アプリケーション・インストーラーをダウンロードしています...",
    runInstaller     : "Connect アプリケーション・インストーラーを実行してください。",
    stepOne          : "ステップ 1",
    stepTwo          : "ステップ 2",
    stepThree        : "ステップ 3",
    how              : "方法",
    new              : "新規",
    installAddon     : "アドオンのインストール",
    installExtension : "拡張機能のインストール",
    enableExtension  : "拡張機能の有効化",
    required         : "必須ステップ",
    downloadConnect  : "Connect のダウンロード",
    downloadApp      : "アプリケーションのダウンロード",
    installConnect   : "Connect のインストール",
    upgradeConnect   : "Connect のアップグレード",
    notSupported     : "このブラウザーは、IBM Aspera Connect でサポートされていません。 サポートされるブラウザーのリストについては、<a>ここをクリック</a>してください。",
    previousVersion  : "前のバージョンに戻す"
  },
  'ko': {
    launching        : "IBM Aspera Connect 시작 중...",
    installOnSafari  : "IBM Aspera Connect가 설치되면 브라우저를 다시 시작하십시오.",
    retryButton      : "재시도",
    retry            : "Connect에 연결할 수 없음",
    running          : "IBM Aspera Connect가 실행 중입니다!",
    alreadyInstalled : "이미 설치하셨습니까?",
    troubleshoot     : "문제점 해결",
    refreshButton    : "새로 고치기",
    bannerTitle      : "Aspera 업로드 및 다운로드를 사용하려면 IBM Aspera Connect {3.9.1}을 설치 또는 업그레이드해야 합니다.",
    tryRestarting    : "브라우저를 다시 시작해 보십시오.",
    pleaseDownload   : "잠시 대기하십시오. Connect 앱 설치 프로그램을 다운로드하는 중입니다...",
    runInstaller     : "Connect 앱 설치 프로그램을 실행하십시오.",
    stepOne          : "1단계",
    stepTwo          : "2단계",
    stepThree        : "3단계",
    how              : "방법",
    new              : "신규",
    installAddon     : "추가 기능 설치",
    installExtension : "확장 기능 설치",
    enableExtension  : "확장 기능 사용",
    required         : "필수 단계",
    downloadConnect  : "Connect 다운로드",
    downloadApp      : "앱 다운로드",
    installConnect   : "Connect 설치",
    upgradeConnect   : "Connect 업그레이드",
    notSupported     : "이 브라우저는 IBM Aspera Connect에서 지원하지 않습니다. 지원되는 브라우저 목록은 <a>여기를 클릭</a>하십시오.",
    previousVersion  : "이전 버전으로 돌아가십시오."
  },
  'zh-CN': {
    launching        : "正在启动 IBM Aspera Connect...",
    installOnSafari  : "IBM Aspera Connect 安装完成后，请重新启动浏览器。",
    retryButton      : "重试",
    retry            : "无法连接 Connect",
    running          : "IBM Aspera Connect 正在运行！",
    alreadyInstalled : "已安装？",
    troubleshoot     : "疑难解答",
    refreshButton    : "刷新",
    bannerTitle      : "要启用 Aspera 上传和下载，您必须安装或升级 IBM Aspera Connect {3.9.1}。",
    tryRestarting    : "或者，请尝试重新启动浏览器。",
    pleaseDownload   : "请稍等。正在下载 Connect 应用安装程序...",
    runInstaller     : "请运行 Connect 应用安装程序",
    stepOne          : "第 1 步",
    stepTwo          : "第 2 步",
    stepThree        : "第 3 步",
    how              : "如何？",
    new              : "新的",
    installAddon     : "安装附加组件",
    installExtension : "安装扩展",
    enableExtension  : "启用扩展",
    required         : "必要步骤",
    downloadConnect  : "下载 Connect",
    downloadApp      : "下载应用",
    installConnect   : "安装 Connect",
    upgradeConnect   : "升级 Connect",
    notSupported     : "IBM Aspera Connect 不支持此浏览器。要获取受支持浏览器列表，请<a>单击此处</a>。",
    previousVersion  : "尝试返回至先前版本。"
  }
};

let locale = Translations[Utils.locale()] || Translations['en-US'];

const Constants = {
  bannerStrings: locale
};

export default Constants;